Adds a terraform example
stackhpc/ansible-slurm-appliance pull request #19
Opened 2021-02-17 16:37 UTC by jovial

Possibly needs some work on the docs before merging. Currently just using what we have in skeleton.

2021-03-10 10:25 UTC, sjpb commented
README for this should probably be updated by deleting a lot of it once #37 is merged.

2021-03-10 10:34 UTC, sjpb requested changes
README should really be updated/simplified after merging #37

2021-03-10 10:34 UTC, sjpb commented on environments/terraform-example/inventory/groups
> +# FIXME: development cluster is currently not setup to use dedicated login nodes
Logic assumes login != control so groups here and above comment need changing.

2021-03-10 10:34 UTC, sjpb commented on environments/terraform-example/inventory/groups
> +[podman:children]
Looks like this needs refreshing from the latest `layouts/everything`?

2021-03-10 10:34 UTC, sjpb commented on environments/terraform-example/.gitignore
> +inventory/hosts
What's the basis for gitignoring this? Just that it's really controlled by terraform?

2021-03-30 11:28 UTC, sjpb commented
This needs a separate control node.

2021-03-30 11:33 UTC, sjpb commented
Actually - I think it'll work just setting `openhpc_login_only_nodes: ''` in e.g `environments/terraform-example/inventory/group_vars/all/openhpc.yml`.

Not sure the groups are consistent with the `minimal` skelton though.

2021-05-28 14:57 UTC, brtknr commented
I rebased this on master but didn't have any conflict. I have moved the terraform example to cookiecutter folder since the README in the cookiecutter references terraform.

2021-05-28 15:01 UTC, jovial reviewed
Looks good to me, but I can;t approve my own PR.

2021-07-16 12:55 UTC, JohnGarbutt approved these changes

2021-07-16 13:30 UTC, merged

2021-07-16 19:45 UTC, sjpb commented
I haven't actually looked at this yet (sorry) but there's a fairly sophisticated terraform example [here](https://github.com/stackhpc/ansible-slurm-appliance/tree/nrel-workshop/environments/nrel-workshop/terraform) including cluster network definition, multiple compute node types, per-node overrides for images, and auto-generation of partition info from compute node types. All that came out of experience setting up NREL ...

2021-07-16 19:46 UTC, sjpb commented
> ... since the README in the cookiecutter references terraform.

It won't after #85 but I'm not adverse to including TF as a default - otherwise getting started is quite hard!