Add freeipa (not containerised)
stackhpc/ansible-slurm-appliance pull request #241
Opened 2022-12-02 09:59 UTC by sjpb

NB this doesn't use a "fat" image as OOD package installs apache config which appears to break the GUI.

2023-06-29 16:35 UTC, sjpb commented
TODO - fix whatever the ordering issue was with iam and filesystems.yml in the lab.

2023-11-02 07:43 UTC, m-bull requested changes

2023-11-02 07:43 UTC, m-bull commented on ansible/adhoc/backup-keytabs.yml
> +# Use ONE of the following tags on this playbook:
Could this be made an extravar instead e.g. `backup_keytabs_action=deploy`? I think it would make it easier when we come to use this with Azimuth.

2023-11-02 07:43 UTC, m-bull commented on ansible/bootstrap.yml
> +    - name: Install freeipa server
```suggestion
    - name: Install FreeIPA server
```

2023-11-02 07:43 UTC, m-bull commented on ansible/fatimage.yml
> +    - name: Install freeipa client
```suggestion
    - name: Install FreeIPA client
```

2023-11-02 07:43 UTC, m-bull commented on ansible/iam.yml
> +    - name: Add freeipa hosts
```suggestion
    - name: Ensure FreeIPA client hosts are added to the FreeIPA server
```

2023-11-02 07:43 UTC, m-bull commented on ansible/iam.yml
> +    - name: Install freeipa client
```suggestion
    - name: Install FreeIPA client
```

2023-11-02 07:43 UTC, m-bull commented on ansible/iam.yml
> +    - name: Enrole freeipa clients
```suggestion
    - name: Enrol FreeIPA clients
```

2023-11-02 07:43 UTC, m-bull commented on ansible/iam.yml
> +        tasks_from: enrole.yml
```suggestion
        tasks_from: enrol.yml
```

Needs corresponding change of filename

2023-11-02 07:43 UTC, m-bull commented on ansible/iam.yml
> +    - name: Add freeipa users
```suggestion
    - name: Add FreeIPA users
```

2023-11-02 07:43 UTC, m-bull commented on ansible/roles/freeipa/README.md
> +- Hosts discover the FreeIPA server FQDN (and their own domain) from DNS records. If this is not set from DHCP, then use the `resolv_conf` role to configure this. For example when using the in-applia
```suggestion
- Hosts discover the FreeIPA server FQDN (and their own domain) from DNS records. If DNS servers are not set from correctly by DHCP, use the `resolv_conf` role to configure this. For example when using the in-appliance FreeIPA development server,:
```

2023-11-02 07:43 UTC, m-bull commented on ansible/roles/freeipa/README.md
> +- For production use with an external FreeIPA server, a random one-time password (OTP) must be generated when adding hosts to FreeIPA (e.g. using `ipa host-add --random ...`). This password should be
```suggestion
- For production use with an external FreeIPA server, a random one-time password (OTP) must be generated when adding hosts to FreeIPA (e.g. using `ipa host-add --random ...`). This password should be set as a hostvar `freeipa_host_password`. Initial host enrolment will use this OTP to enrol the host. After this, it becomes irrelevant so it does not need to be committed to git. This approach means the appliance does not require the FreeIPA administrator password.
```

2023-11-02 07:43 UTC, m-bull commented on ansible/roles/freeipa/tasks/addhost.yml
> +    ipa_user: admin
Is this always `admin` - should it be parameterised?

2023-11-02 07:43 UTC, m-bull commented on ansible/roles/freeipa/tasks/backup-keytabs.yml
> +  tags: retrieve
Other side to setting this as an extravar:

`when:` etc

2023-11-02 07:43 UTC, m-bull commented on ansible/roles/freeipa/tasks/enrole.yml
> +- name: Renrole with FreeIPA using backed-up keytab
```suggestion
- name: Re-enrol with FreeIPA using backed-up keytab
```

2023-11-02 07:43 UTC, m-bull commented on ansible/roles/freeipa/tasks/enrole.yml
> +  # renrolement means:
```suggestion
  # re-enrolement means:
```

2023-11-02 07:43 UTC, m-bull commented on ansible/roles/freeipa/tasks/enrole.yml
> +  # reenrolment requires --force-join and --password, or --keytab
```suggestion
  # re-enrolment requires --force-join and --password, or --keytab
```

2023-11-02 07:43 UTC, m-bull commented on ansible/roles/freeipa/tasks/enrole.yml
> +- name: Enrole with FreeIPA using random password
```suggestion
- name: Enrol with FreeIPA using random password
```

2023-11-02 07:43 UTC, m-bull commented on ansible/roles/freeipa/tasks/server.yml
> +- name: Disable redirects to hard-coded domain
I understand why this is necessary, but its a bit grim!

2023-11-02 07:43 UTC, m-bull commented on ansible/roles/freeipa/tasks/users.yml
> +  community.general.ipa_user: "{{ freeipa_user_defaults | combine(item) }}"
Splatting args like this causes a warning - any chance you could split out the arguments that you want to use?

2023-11-08 09:44 UTC, merged