Pin python package versions and update pips
stackhpc/ansible-slurm-appliance pull request #304
Opened 2023-08-29 13:40 UTC by sd109

2023-08-29 14:21 UTC, sd109 commented
Manually tested (via CaaS Slurm appliance branch [here](https://github.com/stackhpc/caas-slurm-appliance/compare/main...fix/ood-pip-update)) but happy to wait for SMS to be fixed so that proper CI can run before merging if preferred.

2023-09-04 15:33 UTC, JohnGarbutt commented on ansible/roles/openondemand/tasks/vnc_compute.yml
> +    state: latest
shouldn't we pin this to a specific version as well? pip can break things.

2023-09-05 08:20 UTC, sjpb requested changes

2023-09-05 08:20 UTC, sjpb commented on ansible/roles/openondemand/tasks/vnc_compute.yml
> +    state: 23.2.1
Passing a version to `state` is [not documented](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html#parameter-state) as working

2023-09-05 15:59 UTC, sjpb commented
@sd109 which makes me wonder if there should be a `pip_version` default in environments/common/inventory/group_vars/defaults which everything could use?

2023-09-05 16:08 UTC, sd109 commented
Yeah probably, I'll make sure this CI actually passes then make that change.

2023-09-08 14:10 UTC, sjpb commented
Turns out this was fixed by https://github.com/stackhpc/ansible-slurm-appliance/pull/294 but CaaS hadn't been updated to include that.

2023-09-08 14:10 UTC, closed without merging