Avoid prompting user to accept hostkey in OOD shell
stackhpc/ansible-slurm-appliance pull request #331
Opened 2023-11-28 15:38 UTC by sjpb

... by adding the host's key to global known hosts.

2023-12-07 16:18 UTC, sd109 requested changes

2023-12-07 16:18 UTC, sd109 commented on ansible/roles/openondemand/tasks/main.yml
> +- name: Add login hostkey to known hosts
Should we use line_in_file here instead of copy?

2023-12-08 13:21 UTC, sjpb commented
@sd109  tested, works, is idempotent.

2023-12-12 10:40 UTC, sd109 approved these changes
LGTM

2023-12-12 10:40 UTC, sd109 commented on ansible/roles/openondemand/tasks/main.yml
> +    marker: "# {mark} ANSIBLE MANGED BLOCK: openondemand login host" # allows other tasks to use blockinfile on this file
```suggestion
    marker: "# {mark} ANSIBLE MANAGED BLOCK: openondemand login host" # allows other tasks to use blockinfile on this file
```

2023-12-12 10:40 UTC, sd109 approved these changes

2023-12-15 11:25 UTC, merged