Add TuneD
stackhpc/ansible-slurm-appliance pull request #409
Opened 2024-07-09 08:39 UTC by bertiethorpe

2024-07-09 08:56 UTC, sjpb commented
image build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/9854015715

2024-07-12 09:23 UTC, sd109 approved these changes
LGTM other than README

2024-07-18 09:55 UTC, sjpb requested changes

2024-07-18 09:55 UTC, sjpb commented on ansible/roles/tuned/README.md
> +To list all available profiles and identify the current active profile, run on-node:
I'd remove this and below - this is tuned stuff not role stuff.

2024-07-18 11:01 UTC, sjpb approved these changes

2024-07-18 12:18 UTC, merged