Nightly Slurm CI Rocky update workflow
stackhpc/ansible-slurm-appliance pull request #440
Opened 2024-09-18 12:39 UTC by bertiethorpe

2024-09-30 14:28 UTC, bertiethorpe commented
Successful nightly build and image sharing between clouds:

https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/11106417297

2024-10-01 18:45 UTC, bertiethorpe commented
Successful nightly build and image sharing between clouds:

https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/11129155877/job/30928488462

2024-10-01 20:53 UTC, bertiethorpe commented
First successful new fatimage build on SMS:
https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/11131571980

RL8 - 1h 19m 8s
RL9 - 1h 9m 23s
RL9-cuda - 1h 34m 40s

2024-10-02 14:14 UTC, bertiethorpe commented
new fatimage build on Leafcloud:
https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/11136671437

RL8 - 49m 33s
RL9 - 39m 16s
RL9-cuda - 1h 9m 31s

2024-10-03 15:40 UTC, bertiethorpe commented
Fatimage leafcloud build after moving trivy scan to separate workflow:
https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/11162164400

Run time: 35m

2024-10-04 12:39 UTC, bertiethorpe commented
Trivy scan on push works:
https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/11177947378

2024-10-08 13:06 UTC, sjpb requested changes
Some minor nits.

2024-10-08 13:07 UTC, sjpb commented on .github/workflows/fatimage.yml
> +          if [[ "${{ matrix.build }}" == *"cuda"* ]]; then
TBD - am going to provide another response on this.

2024-10-08 13:35 UTC, sjpb commented on ansible/bootstrap.yml
> +      command: dnf -y remove cockpit-ws
From @bertiethorpe:

> This was in the PR from when random packer build tasks got a lot slower. This was a suggestion from Matt A if I remember correctly. I can't remember if it was this in the end, but packer builds starting speeding up again after I did it

2024-10-08 13:36 UTC, sjpb commented on ansible/bootstrap.yml
> +      command: dnf -y remove cockpit-ws
Ok could you just add a comment in to that effect then pls.

2024-10-09 12:09 UTC, bertiethorpe commented
fat image build:
https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/11253430727

2024-10-09 15:06 UTC, sjpb requested changes

2024-10-09 15:06 UTC, sjpb commented on .github/workflows/fatimage.yml
> +          SOURCE_IMAGE=${{ fromJSON(env.SOURCE_IMAGES_MAP)[matrix.os_version][matrix.build] }}
Would this not be cleaner in the task's env? If its not at the top-level env.

2024-10-09 15:06 UTC, sjpb commented on .github/workflows/nightlybuild.yml
> +          SOURCE_IMAGE=${{ fromJSON(env.SOURCE_IMAGES_MAP)[matrix.os_version] }}
As for same in fatimage.

2024-10-09 15:06 UTC, sjpb commented on packer/openstack.pkr.hcl
>  variable "source_image" {
This needs to NOT be a map any more, same as source_image_name. Should still have default of null though.

2024-10-09 16:00 UTC, bertiethorpe commented
https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/11258069062

2024-10-10 10:26 UTC, sjpb approved these changes
LGTM

2024-10-10 10:26 UTC, merged