Pin nvidia-driver and cuda packages to working packages
stackhpc/ansible-slurm-appliance pull request #496
Opened 2024-12-13 13:26 UTC by sjpb

- Pins nvidia-driver and cuda packages to avoid a dnf depsolve error on install
- Makes installing cuda packages optional
- Only run nvidia-driver/cuda installs during image build
- Extend CI extra build test to also include cuda role

Depsolve error with `565-open` nvidia-driver stream was:
```
Depsolve Error occurred: 
 Problem: package cuda-12-6-12.6.3-1.x86_64 from cuda-rhel9-x86_64 requires cuda-runtime-12-6 >= 12.6.3, but none of the providers can be installed
...
```

2024-12-16 15:14 UTC, wtripp180901 requested changes
some nitpicks but otherwise LGTM

2024-12-16 15:14 UTC, wtripp180901 commented on ansible/roles/cuda/defaults/main.yml
> -cuda_distro: "rhel{{ ansible_distribution_major_version }}"
why was this removed despite its templated value being duplicated elsewhere? Maybe private var instead if we don't want it to be overridden

2024-12-16 15:14 UTC, wtripp180901 commented on ansible/roles/cuda/defaults/main.yml
> +cuda_driver_stream: '560-open' # 565-open has problems with cuda packages
nitpick but `cuda_nvidia_driver_stream` might be a better name to make it clearer that people shouldn't be looking for cuda-specific drivers

2024-12-16 15:16 UTC, wtripp180901 commented
have we been able to test cuda on any GPU nodes yet btw?

2024-12-18 16:55 UTC, sjpb commented
Image build: https://github.com/stackhpc/ansible-slurm-appliance/actions/runs/12397634280

2024-12-19 08:52 UTC, wtripp180901 approved these changes
LGTM assuming CI passes

2024-12-19 10:09 UTC, merged